// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	payment.proto
	payment_common.proto

It has these top-level messages:
	GetPaymentRequest
	GetPaymentReply
	GetPaymentListRequest
	GetPaymentListReply
	CreatePaymentRequest
	CreatePaymentReply
	PaymentInformation
	FinishPaymentRequest
	FinishPaymentReply
	Error
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PaymentStatus int32

const (
	PaymentStatus_Unknown   PaymentStatus = 0
	PaymentStatus_NotPay    PaymentStatus = 1
	PaymentStatus_Completed PaymentStatus = 6
)

var PaymentStatus_name = map[int32]string{
	0: "Unknown",
	1: "NotPay",
	6: "Completed",
}
var PaymentStatus_value = map[string]int32{
	"Unknown":   0,
	"NotPay":    1,
	"Completed": 6,
}

func (x PaymentStatus) String() string {
	return proto.EnumName(PaymentStatus_name, int32(x))
}
func (PaymentStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetPaymentRequest struct {
	PaymentId uint64 `protobuf:"varint,1,opt,name=paymentId" json:"paymentId,omitempty"`
	ShopId    uint64 `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *GetPaymentRequest) Reset()                    { *m = GetPaymentRequest{} }
func (m *GetPaymentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPaymentRequest) ProtoMessage()               {}
func (*GetPaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetPaymentRequest) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *GetPaymentRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetPaymentReply struct {
	Err                *Error              `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	PaymentInformation *PaymentInformation `protobuf:"bytes,2,opt,name=paymentInformation" json:"paymentInformation,omitempty"`
}

func (m *GetPaymentReply) Reset()                    { *m = GetPaymentReply{} }
func (m *GetPaymentReply) String() string            { return proto.CompactTextString(m) }
func (*GetPaymentReply) ProtoMessage()               {}
func (*GetPaymentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetPaymentReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetPaymentReply) GetPaymentInformation() *PaymentInformation {
	if m != nil {
		return m.PaymentInformation
	}
	return nil
}

type GetPaymentListRequest struct {
	ShopId   uint64        `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	Status   PaymentStatus `protobuf:"varint,2,opt,name=status,enum=payment.pkg.rpc.protos.PaymentStatus" json:"status,omitempty"`
	Page     uint64        `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize uint64        `protobuf:"varint,4,opt,name=pageSize" json:"pageSize,omitempty"`
	Scene    uint32        `protobuf:"varint,5,opt,name=scene" json:"scene,omitempty"`
}

func (m *GetPaymentListRequest) Reset()                    { *m = GetPaymentListRequest{} }
func (m *GetPaymentListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPaymentListRequest) ProtoMessage()               {}
func (*GetPaymentListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetPaymentListRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *GetPaymentListRequest) GetStatus() PaymentStatus {
	if m != nil {
		return m.Status
	}
	return PaymentStatus_Unknown
}

func (m *GetPaymentListRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetPaymentListRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetPaymentListRequest) GetScene() uint32 {
	if m != nil {
		return m.Scene
	}
	return 0
}

type GetPaymentListReply struct {
	Err                    *Error                `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	PaymentInformationList []*PaymentInformation `protobuf:"bytes,2,rep,name=paymentInformationList" json:"paymentInformationList,omitempty"`
	Count                  uint64                `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *GetPaymentListReply) Reset()                    { *m = GetPaymentListReply{} }
func (m *GetPaymentListReply) String() string            { return proto.CompactTextString(m) }
func (*GetPaymentListReply) ProtoMessage()               {}
func (*GetPaymentListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetPaymentListReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetPaymentListReply) GetPaymentInformationList() []*PaymentInformation {
	if m != nil {
		return m.PaymentInformationList
	}
	return nil
}

func (m *GetPaymentListReply) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreatePaymentRequest struct {
	ShopId uint64 `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	Amount uint64 `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	Note   string `protobuf:"bytes,4,opt,name=note" json:"note,omitempty"`
}

func (m *CreatePaymentRequest) Reset()                    { *m = CreatePaymentRequest{} }
func (m *CreatePaymentRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePaymentRequest) ProtoMessage()               {}
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreatePaymentRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *CreatePaymentRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreatePaymentRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreatePaymentRequest) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

type CreatePaymentReply struct {
	Err     *Error              `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Payment *PaymentInformation `protobuf:"bytes,2,opt,name=payment" json:"payment,omitempty"`
}

func (m *CreatePaymentReply) Reset()                    { *m = CreatePaymentReply{} }
func (m *CreatePaymentReply) String() string            { return proto.CompactTextString(m) }
func (*CreatePaymentReply) ProtoMessage()               {}
func (*CreatePaymentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreatePaymentReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *CreatePaymentReply) GetPayment() *PaymentInformation {
	if m != nil {
		return m.Payment
	}
	return nil
}

type PaymentInformation struct {
	PaymentId  uint64        `protobuf:"varint,1,opt,name=paymentId" json:"paymentId,omitempty"`
	ShopId     uint64        `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
	UserId     uint64        `protobuf:"varint,3,opt,name=userId" json:"userId,omitempty"`
	Amount     uint64        `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	Note       string        `protobuf:"bytes,5,opt,name=note" json:"note,omitempty"`
	Status     PaymentStatus `protobuf:"varint,6,opt,name=status,enum=payment.pkg.rpc.protos.PaymentStatus" json:"status,omitempty"`
	CreateTime int64         `protobuf:"varint,7,opt,name=createTime" json:"createTime,omitempty"`
}

func (m *PaymentInformation) Reset()                    { *m = PaymentInformation{} }
func (m *PaymentInformation) String() string            { return proto.CompactTextString(m) }
func (*PaymentInformation) ProtoMessage()               {}
func (*PaymentInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PaymentInformation) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *PaymentInformation) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *PaymentInformation) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PaymentInformation) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PaymentInformation) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *PaymentInformation) GetStatus() PaymentStatus {
	if m != nil {
		return m.Status
	}
	return PaymentStatus_Unknown
}

func (m *PaymentInformation) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type FinishPaymentRequest struct {
	PaymentId uint64 `protobuf:"varint,1,opt,name=paymentId" json:"paymentId,omitempty"`
}

func (m *FinishPaymentRequest) Reset()                    { *m = FinishPaymentRequest{} }
func (m *FinishPaymentRequest) String() string            { return proto.CompactTextString(m) }
func (*FinishPaymentRequest) ProtoMessage()               {}
func (*FinishPaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FinishPaymentRequest) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

type FinishPaymentReply struct {
	Err     *Error              `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Payment *PaymentInformation `protobuf:"bytes,2,opt,name=payment" json:"payment,omitempty"`
}

func (m *FinishPaymentReply) Reset()                    { *m = FinishPaymentReply{} }
func (m *FinishPaymentReply) String() string            { return proto.CompactTextString(m) }
func (*FinishPaymentReply) ProtoMessage()               {}
func (*FinishPaymentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *FinishPaymentReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *FinishPaymentReply) GetPayment() *PaymentInformation {
	if m != nil {
		return m.Payment
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPaymentRequest)(nil), "payment.pkg.rpc.protos.GetPaymentRequest")
	proto.RegisterType((*GetPaymentReply)(nil), "payment.pkg.rpc.protos.GetPaymentReply")
	proto.RegisterType((*GetPaymentListRequest)(nil), "payment.pkg.rpc.protos.GetPaymentListRequest")
	proto.RegisterType((*GetPaymentListReply)(nil), "payment.pkg.rpc.protos.GetPaymentListReply")
	proto.RegisterType((*CreatePaymentRequest)(nil), "payment.pkg.rpc.protos.CreatePaymentRequest")
	proto.RegisterType((*CreatePaymentReply)(nil), "payment.pkg.rpc.protos.CreatePaymentReply")
	proto.RegisterType((*PaymentInformation)(nil), "payment.pkg.rpc.protos.PaymentInformation")
	proto.RegisterType((*FinishPaymentRequest)(nil), "payment.pkg.rpc.protos.FinishPaymentRequest")
	proto.RegisterType((*FinishPaymentReply)(nil), "payment.pkg.rpc.protos.FinishPaymentReply")
	proto.RegisterEnum("payment.pkg.rpc.protos.PaymentStatus", PaymentStatus_name, PaymentStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PaymentController service

type PaymentControllerClient interface {
	// 获取Payment
	GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentReply, error)
	// 获取Payment列表
	GetPaymentList(ctx context.Context, in *GetPaymentListRequest, opts ...grpc.CallOption) (*GetPaymentListReply, error)
	// 创建Payment
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentReply, error)
	// 完成订单
	FinishPayment(ctx context.Context, in *FinishPaymentRequest, opts ...grpc.CallOption) (*FinishPaymentReply, error)
}

type paymentControllerClient struct {
	cc *grpc.ClientConn
}

func NewPaymentControllerClient(cc *grpc.ClientConn) PaymentControllerClient {
	return &paymentControllerClient{cc}
}

func (c *paymentControllerClient) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentReply, error) {
	out := new(GetPaymentReply)
	err := grpc.Invoke(ctx, "/payment.pkg.rpc.protos.PaymentController/GetPayment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentControllerClient) GetPaymentList(ctx context.Context, in *GetPaymentListRequest, opts ...grpc.CallOption) (*GetPaymentListReply, error) {
	out := new(GetPaymentListReply)
	err := grpc.Invoke(ctx, "/payment.pkg.rpc.protos.PaymentController/GetPaymentList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentControllerClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentReply, error) {
	out := new(CreatePaymentReply)
	err := grpc.Invoke(ctx, "/payment.pkg.rpc.protos.PaymentController/CreatePayment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentControllerClient) FinishPayment(ctx context.Context, in *FinishPaymentRequest, opts ...grpc.CallOption) (*FinishPaymentReply, error) {
	out := new(FinishPaymentReply)
	err := grpc.Invoke(ctx, "/payment.pkg.rpc.protos.PaymentController/FinishPayment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PaymentController service

type PaymentControllerServer interface {
	// 获取Payment
	GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentReply, error)
	// 获取Payment列表
	GetPaymentList(context.Context, *GetPaymentListRequest) (*GetPaymentListReply, error)
	// 创建Payment
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentReply, error)
	// 完成订单
	FinishPayment(context.Context, *FinishPaymentRequest) (*FinishPaymentReply, error)
}

func RegisterPaymentControllerServer(s *grpc.Server, srv PaymentControllerServer) {
	s.RegisterService(&_PaymentController_serviceDesc, srv)
}

func _PaymentController_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentControllerServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.pkg.rpc.protos.PaymentController/GetPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentControllerServer).GetPayment(ctx, req.(*GetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentController_GetPaymentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentControllerServer).GetPaymentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.pkg.rpc.protos.PaymentController/GetPaymentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentControllerServer).GetPaymentList(ctx, req.(*GetPaymentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentController_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentControllerServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.pkg.rpc.protos.PaymentController/CreatePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentControllerServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentController_FinishPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentControllerServer).FinishPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.pkg.rpc.protos.PaymentController/FinishPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentControllerServer).FinishPayment(ctx, req.(*FinishPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "payment.pkg.rpc.protos.PaymentController",
	HandlerType: (*PaymentControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayment",
			Handler:    _PaymentController_GetPayment_Handler,
		},
		{
			MethodName: "GetPaymentList",
			Handler:    _PaymentController_GetPaymentList_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _PaymentController_CreatePayment_Handler,
		},
		{
			MethodName: "FinishPayment",
			Handler:    _PaymentController_FinishPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xce, 0xd6, 0x89, 0xd3, 0x4c, 0x94, 0xfe, 0xe9, 0xfc, 0x21, 0xb2, 0x22, 0x40, 0xd1, 0x4a,
	0x88, 0x10, 0x20, 0x48, 0x01, 0x89, 0x2b, 0x6e, 0x08, 0x07, 0x45, 0x42, 0xa8, 0x72, 0xe1, 0xa6,
	0x37, 0xc8, 0x4d, 0x96, 0xd6, 0x4a, 0xbc, 0x6b, 0xd6, 0x1b, 0xa1, 0xf0, 0x0a, 0xbc, 0x03, 0x4f,
	0xc1, 0x03, 0xc0, 0x03, 0xf1, 0x0e, 0xc8, 0xbb, 0x6e, 0xec, 0x1c, 0xac, 0xa6, 0xbe, 0xe1, 0xca,
	0x9e, 0xd9, 0xf9, 0xe6, 0xf0, 0xed, 0x37, 0x0b, 0x8d, 0xd0, 0x5b, 0x06, 0x8c, 0xab, 0x41, 0x28,
	0x85, 0x12, 0xd8, 0x5e, 0x99, 0xb3, 0x8b, 0x81, 0x0c, 0x27, 0xc6, 0x1d, 0x75, 0x5a, 0x89, 0xff,
	0xd3, 0x44, 0x04, 0x81, 0xe0, 0xc6, 0x4d, 0xc7, 0x70, 0xfc, 0x96, 0xa9, 0x13, 0x73, 0xe4, 0xb2,
	0x2f, 0x0b, 0x16, 0x29, 0xbc, 0x0d, 0xb5, 0x24, 0x78, 0x3c, 0x75, 0x48, 0x97, 0xf4, 0xca, 0x6e,
	0xea, 0xc0, 0x36, 0xd8, 0xd1, 0xa5, 0x08, 0xc7, 0x53, 0xe7, 0x40, 0x1f, 0x25, 0x16, 0xfd, 0x41,
	0xe0, 0xbf, 0x6c, 0xae, 0x70, 0xbe, 0xc4, 0x27, 0x60, 0x31, 0x29, 0x75, 0x8e, 0xfa, 0xf0, 0xce,
	0x60, 0x77, 0x6b, 0x83, 0xd7, 0x52, 0x0a, 0xe9, 0xc6, 0x91, 0x78, 0x06, 0x78, 0x55, 0x89, 0x7f,
	0x16, 0x32, 0xf0, 0x94, 0x2f, 0xb8, 0x2e, 0x54, 0x1f, 0xf6, 0xf3, 0xf0, 0x27, 0x5b, 0x08, 0x77,
	0x47, 0x16, 0xfa, 0x93, 0xc0, 0xad, 0xb4, 0xc1, 0x77, 0x7e, 0xb4, 0x1a, 0x38, 0x1d, 0x89, 0x64,
	0x47, 0xc2, 0x17, 0x60, 0x47, 0xca, 0x53, 0x8b, 0x48, 0x77, 0x70, 0x34, 0xbc, 0x77, 0x4d, 0x07,
	0xa7, 0x3a, 0xd8, 0x4d, 0x40, 0x88, 0x50, 0x0e, 0xbd, 0x0b, 0xe6, 0x58, 0x3a, 0xa9, 0xfe, 0xc7,
	0x0e, 0x1c, 0xc6, 0xdf, 0x53, 0xff, 0x1b, 0x73, 0xca, 0xda, 0xbf, 0xb2, 0xb1, 0x05, 0x95, 0x68,
	0xc2, 0x38, 0x73, 0x2a, 0x5d, 0xd2, 0x6b, 0xb8, 0xc6, 0xa0, 0xbf, 0x08, 0xfc, 0xbf, 0xd9, 0x76,
	0x21, 0x6e, 0xcf, 0xa1, 0xbd, 0xcd, 0x4a, 0x9c, 0xcf, 0x39, 0xe8, 0x5a, 0x37, 0xe4, 0x37, 0x27,
	0x53, 0x3c, 0xc2, 0x44, 0x2c, 0xb8, 0x4a, 0x66, 0x36, 0x06, 0x95, 0xd0, 0x1a, 0x49, 0xe6, 0x29,
	0xb6, 0x21, 0xb4, 0x3c, 0xde, 0xdb, 0x60, 0x2f, 0x22, 0x26, 0x53, 0x89, 0x19, 0x2b, 0xf6, 0x7b,
	0x41, 0x26, 0x7d, 0x62, 0xc5, 0x44, 0x73, 0xa1, 0x0c, 0xa1, 0x35, 0x57, 0xff, 0xd3, 0xef, 0x04,
	0x70, 0xa3, 0x68, 0x21, 0xd6, 0x5e, 0x41, 0x35, 0x09, 0x2a, 0x20, 0xc3, 0x2b, 0x28, 0xfd, 0x43,
	0x00, 0xb7, 0xcf, 0x8b, 0x6d, 0x5a, 0x86, 0x1e, 0x2b, 0x87, 0x9e, 0xf2, 0x4e, 0x7a, 0x2a, 0x29,
	0x3d, 0x19, 0x69, 0xdb, 0x45, 0xa4, 0x7d, 0x17, 0x60, 0xa2, 0xc9, 0xfd, 0xe0, 0x07, 0xcc, 0xa9,
	0x76, 0x49, 0xcf, 0x72, 0x33, 0x1e, 0xfa, 0x0c, 0x5a, 0x6f, 0x7c, 0xee, 0x47, 0x97, 0x37, 0x79,
	0x5a, 0xf4, 0x9d, 0x6d, 0xc0, 0xfe, 0xdd, 0x9d, 0xf5, 0x9f, 0x43, 0x63, 0x6d, 0x78, 0xac, 0x43,
	0xf5, 0x23, 0x9f, 0x71, 0xf1, 0x95, 0x37, 0x4b, 0x08, 0x60, 0xbf, 0x17, 0xf1, 0x56, 0x36, 0x09,
	0x36, 0xa0, 0x36, 0x12, 0x41, 0x38, 0x67, 0x8a, 0x4d, 0x9b, 0xf6, 0xf0, 0xb7, 0x05, 0xc7, 0x09,
	0x72, 0x24, 0xb8, 0x92, 0x62, 0x3e, 0x67, 0xf1, 0xfa, 0x41, 0xba, 0xc6, 0xf8, 0x20, 0xaf, 0xa3,
	0xad, 0xe7, 0xb8, 0x73, 0x7f, 0x9f, 0xd0, 0x70, 0xbe, 0xa4, 0x25, 0xe4, 0x70, 0xb4, 0xfe, 0x54,
	0xe0, 0xe3, 0xeb, 0xc1, 0x99, 0x97, 0xb0, 0xf3, 0x70, 0xdf, 0x70, 0x53, 0x6f, 0x06, 0x8d, 0xb5,
	0x1d, 0xc3, 0x47, 0x79, 0xf8, 0x5d, 0xfb, 0xdf, 0xe9, 0xef, 0x19, 0xbd, 0x2a, 0xb6, 0x26, 0x8e,
	0xfc, 0x62, 0xbb, 0xa4, 0x97, 0x5f, 0x6c, 0x5b, 0x71, 0xb4, 0xf4, 0xf2, 0xf0, 0xcc, 0x36, 0xc7,
	0xe7, 0xe6, 0xfb, 0xf4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x0e, 0x21, 0x4d, 0x68, 0x07,
	0x00, 0x00,
}
